name: questions_answers
version: 0.0.1
description: >
  Q&A app written with Dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  http: '>=0.11.1 <0.12.0'
  logging: '>=0.11.1 <0.12.0'
  logging_handlers: ">=0.8.0 <0.9.0"
  rpc: '>=0.5.0 <0.6.0'
